name = "GridapODEsTests.jl"
authors = ["Oriol Colomes"]

[deps]
DrWatson = "634d3b9d-ee7a-5ddf-bec9-22491ea816e1"
Gridap = "56d4f2e9-7ea1-5844-9cf6-b9c51ca7ce8e"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
TimerOutputs = "a759f4b9-e2f1-59dc-863e-4aeb61b1ea8f"

[compat]
DrWatson = "2.12.7"
julia = "1.9.2"
